name: Manual Publish to Test PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional)'
        required: false
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    # 注意：不要添加 id-token: write 权限，因为我们使用API token而不是Trusted Publishing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Build package
      run: python -m build
      
    - name: Display version info
      if: github.event.inputs.version != ''
      run: |
        echo "Publishing version: ${{ github.event.inputs.version }}"
      
    - name: Publish package to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
